version: '3.7'
services:
  server:
    image: ghcr.io/khanh29204/code-push-server:latest
    volumes:
      - ./data:/data
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - redis
    # Lệnh chạy khởi tạo DB trước khi start server
    command: sh -c "bun bin/db.js init && bun bin/www.js"


  # MySQL service đã bị xóa

  redis:
    image: redis:latest
    volumes:
      - ./data-redis:/data